const nodemailer = require('nodemailer');
const { Contact } = require('../model/contactModel');

const transporter = nodemailer.createTransport({
  service: process.env.EMAIL_SERVICE,
  auth: {
    user: process.env.EMAIL_ID,
    pass: process.env.EMAIL_PASSWORD
  }
});

const sendMessageController = async (req, res) => {
  const { name, email, message } = req.body;

  if (!name || !email || !message) {
    return res.status(400).json({
      success: false,
      error: 'All fields are required'
    });
  }

  try {
    // Send email to yourself
    const mailToSelf = {
      from: email,
      to: process.env.EMAIL_ID,
      subject: 'New Message from Portfolio Contact Form',
      html: `
              <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);">
                  <div style="background-color: #007BFF; color: white; padding: 20px; text-align: center;">
                    <h1 style="margin: 0; font-size: 24px;">New Message Alert</h1>
                  </div>
                  <div style="padding: 20px;">
                    <p>You have received a new message from your portfolio contact form:</p>
                    <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                      <tr>
                        <td style="font-weight: bold; padding: 10px; border-bottom: 1px solid #ddd; width: 30%;">Name:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #ddd;">${name}</td>
                      </tr>
                      <tr>
                        <td style="font-weight: bold; padding: 10px; border-bottom: 1px solid #ddd;">Email:</td>
                        <td style="padding: 10px; border-bottom: 1px solid #ddd;">${email}</td>
                      </tr>
                      <tr>
                        <td style="font-weight: bold; padding: 10px;">Message:</td>
                        <td style="padding: 10px;">${message}</td>
                      </tr>
                    </table>
                    <p style="margin-top: 20px;">Please review the message and respond as necessary.</p>
                  </div>
                  <div style="background-color: #f4f4f4; padding: 10px 20px; text-align: center; font-size: 12px; color: #666;">
                    <p style="margin: 0;">This is an automated alert generated by your portfolio contact form.</p>
                  </div>
                </div>
              </div>
            `,
    };

    await transporter.sendMail(mailToSelf);

    const newEmail = await Contact.create({
      name: name,
      email: email,
      message: message
    });

    // Send confirmation email to the user
    const mailToUser = {
      from: process.env.EMAIL_ID,
      to: email,
      subject: 'Message Received',
      html: `
              <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);">
                  <div style="background-color: #4CAF50; color: white; padding: 20px; text-align: center;">
                    <h1 style="margin: 0; font-size: 24px;">Thank You for Reaching Out!</h1>
                  </div>
                  <div style="padding: 20px;">
                    <p>Dear <strong>${name}</strong>,</p>
                    <p>Thank you for your message! I have received the following:</p>
                    <blockquote style="border-left: 4px solid #4CAF50; padding-left: 10px; margin: 15px 0; color: #555; font-style: italic;">
                      "${message}"
                    </blockquote>
                    <p>I will review your message and contact you as soon as possible.</p>
                    <p>In the meantime, if you have any urgent concerns, feel free to reach out to me directly.</p>
                    <p>Best regards,</p>
                    <p><strong>Nikhil Sai Ankilla</strong></p>
                  </div>
                  <div style="background-color: #f4f4f4; padding: 10px 20px; text-align: center; font-size: 12px; color: #666;">
                    <p style="margin: 0;">This is an automated response to confirm that I have received your message.</p>
                  </div>
                </div>
              </div>
            `,
    };

    await transporter.sendMail(mailToUser);

    // Respond with success message
    return res.status(200).json({
      success: true,
      message: 'Your message has been sent. Nikhil will contact you soon. Thank you!'
    });

  } catch (error) {
    console.error(error); // Log the error for debugging

    return res.status(500).json({
      success: false,
      error: error.message || 'Failed to send message. Please try again later.'
    });
  }
};

const getAllMessages = async (req, res) => {
  try {
    const allMessages = await Contact.findAll();

    if (allMessages.length === 0) {
      return res.status(404).send({
        success: false,
        error: "No messages found."
      });
    }

    return res.status(200).send({
      success: true,
      data: allMessages
    });
  } catch (error) {
    console.error(error); // Log the error for debugging

    return res.status(500).json({
      success: false,
      error: error.message || 'Failed to retrieve messages. Please try again later.'
    });
  }
};

module.exports = { sendMessageController, getAllMessages };
